### ISSUE TITLE
Item on Click

### ISSUE THREAD

**Issue by creaturerigger** [ax5ui/ax5ui-menu#1]
I am trying to find how to create item on click function out but i could not what am i missing? Can you please give an example how to do it? I tried something like this:

``` js
menu.onLoad = function(){
        $(this).find("[data-menu-item-index]").on('click', function(){            
            var index = $(this).getAttribute("data-menu-item-index");
            if(index == 0){
                do something....
            }
            else if(index == 1){
                do another thing
            }
            else if(index ==2){
                do etc...
            }
        });
    };
```

**Comment by creaturerigger** [comment]
I went to console and found menu's classes and attributes then i composed this and it works well eventhough i still don't have any idea if there is a menuitem.onclick function.:

$('div.ax5-ui-menu').find('.ax-menu-item, .ax-menu-item-html').on('click', function () {
            var index = $(this).attr('data-menu-item-index');
            switch(index){
                case "0":
                    do something;
                    break;
                case "1":
                    do something else;
                    break;
                   .
                   .
                   .
                   .
                default:
                    break;
            }
        });

**Comment by brant-hwang** [comment]
duplicated. https://github.com/ax5ui/ax5ui-kernel/issues
