### ISSUE TITLE
메뉴 아이템이 하나일 경우

### ISSUE THREAD

**Issue by jsveron23** [ax5ui/ax5ui-menu#3]
원래 의도한 것인지 아닌지 모르겠지만, 아이템이 하나만 있을 경우 호버 이벤트가 기본으로 먹혀서 원래 아이템의 배경 색상이 보이지 않습니다.

**Comment by thomasJang** [comment]
캡쳐 하나 올려주시면. 감사하겠습니다.

**Comment by jsveron23** [comment]
브라우저: 구글 크롬 54.0.2840.98 (64-bit)

![screenshot 2016-11-15 14 49 19](https://cloud.githubusercontent.com/assets/156895/20294609/c6b481b4-ab42-11e6-89e4-becd4c50ec57.png)
![screenshot 2016-11-15 14 48 53](https://cloud.githubusercontent.com/assets/156895/20294610/c6b5469e-ab42-11e6-8fd3-abd43b6752e7.png)

첫번째 부터는 무조건 호버 이미지가 나오고 두번째 부터는 하나가 기본으로 반영되어 있습니다. 마우스를 올리지 않은 상황입니다.

**Comment by thomasJang** [comment]
이런 저런 다른 문제들은 해결 하다보니. 늦어졌습니다.
패치된 버전을 받아 확인 해보시면 되겠습니다.

**Comment by jsveron23** [comment]
감사합니다.
